### ISSUE TITLE
Does the scanner support API?

### ISSUE THREAD

**Issue by kymowang** [Atomicorp/gvm#22]
API would listen on 9390 port, but i doesn't. 
p.s. Why gsad listens 443 and 80 on centos 7? The /etc/sysconfig/gsad has no effect on gsad service.

**Comment by cfi-gb** [comment]
9390 is the GMP API port of the manager, not the one of the scanner. If you want to make the GMP API available have a look at the available command line options of the `gvmd` daemon (via `gvmd --help`).

If you need further support on the configuration for such topics like the API you could ask also on https://community.greenbone.net/. Note that it is only unlikely that distro specific questions like the `/etc/sysconfig/gsad` is answered there.

**Comment by atomicturtle** [comment]
This behavior has changed as of the GVM-11 release where it no longer prompts you to pick a port, and the setup utility has changed to reflect this correctly. I havent actually tested what happens if something else is running on 443 yet, but if someone is interested in adding support for selecting the port this is something for a pull request
