### ISSUE TITLE
openvas-scanner doesn't run after initial setup for centos 8

### ISSUE THREAD

**Issue by waldo323** [Atomicorp/gvm#31]
I have installed using the atomic repo on a fresh centos 8 installation with SELinux disabled.
attempts to start the openvas-scanner service are failing.
in /var/log/messages:
openvas-scanner.service: Failed to execute command: No such file or directory
openvas-scanner.service: Failed at step EXEC spawning /usr/sbin/openvassd: No such file or directory

**Comment by waldo323** [comment]
I was able to get openvas-scanner to start by changing a line in /usr/lib/systemd/system/openvas-scanner.service
ExecStart=/usr/sbin/openvassd $SCANNER_SOCKET $SCANNER_MODE $SCANNER_GROUP $SCANNER_OWNER
to 
ExecStart=/usr/sbin/openvas $SCANNER_SOCKET $SCANNER_MODE $SCANNER_GROUP $SCANNER_OWNER

**Comment by willemdh** [comment]
@waldo323 I can confirm this. `/usr/sbin/openvassd` does not seem to exist

**Comment by cfi-gb** [comment]
There isn't a openvas daemon (openvassd) since GVM-11 anymore:

https://community.greenbone.net/t/openvas-open-vulnerability-assessment-scanner/2623

so the previous workaround posted in https://github.com/Atomicorp/gvm/issues/31#issuecomment-693004374 isn't valid / shouldn't be used and might introduce an unexpected behavior / more issues.

Instead the `openvas-scanner.service` should be deleted from this package completely.

**Comment by atomicturtle** [comment]
removed in openvas-scanner-20.8.0-15138

thanks again for the report everyone! Keep em coming
