### ISSUE TITLE
Patch for whole-family scan config bug

### ISSUE THREAD

**Issue by necouchman** [Atomicorp/gvm#53]
I was just wondering if there are plans to back-port the following fixes, or if the solution is just to push forward to the 21.x release?

https://github.com/greenbone/gvmd/pull/1517
https://github.com/greenbone/gsa/pull/2905

These issues currently block me from actually using most of the local vulnerability detection options, because it blocks selecting them in the scan config.

**Comment by atomicturtle** [comment]
Definitely to do this in 21.4.x, which is already up in atomic-testing. Since you've got hands on experience with this issue, could you try a new build with those packages with:

# New install
yum --enablerepo=atomic-testing install gvm

# Upgrade (untested!)
It might work as an upgrade too, which I havent tested yet, so you could try that with:

yum --enablerepo=atomic-testing upgrade

**Comment by atomicturtle** [comment]
I'm going to close this one as presumed fixed now that 21.4.2 is out, but feel free to re-open this if its not the case
